name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore Rock.sln
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
      run: msbuild Rock.sln -p:Configuration=Release
